# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Play Store Release Build"
  lane :playstore do |options|
   supply(
     track: "internal",
     skip_upload_metadata: true,
     skip_upload_images: true,
     skip_upload_screenshots: true
   )
   gradle(
     task: 'bundle',
     build_type: 'Release'
   )
   upload_to_play_store skip_upload_apk:true
  end
end
